<?php

namespace App\Api\v1\Controllers\Admin;

use App\Api\V1\Requests\AddVideoFlavorRequest;
use App\Http\Controllers\Controller;
use App\MediaFile;
use App\Recording;
use Dingo\Api\Routing\Helpers;
use Illuminate\Database\Eloquent\ModelNotFoundException;

class EncodingController extends Controller
{
    use Helpers;
    public function addVideoFlavor(AddVideoFlavorRequest $flavorRequest) {

        try {
            $item = Recording::where(['active' => 1])->findOrFail($flavorRequest->recordingId);
            $mediaFile = new MediaFile();
            $mediaFile->recordingId = $flavorRequest->recordingId;
            $mediaFile->filename = $flavorRequest->filename;
            $mediaFile->filesize = $flavorRequest->filesize;
            $mediaFile->duration = $flavorRequest->duration;
            $mediaFile->bitrate = $flavorRequest->bitrate;
            $mediaFile->videoWidth = $flavorRequest->width;
            $mediaFile->videoHeight = $flavorRequest->height;
            $mediaFile->videoBitrate= $flavorRequest->bitrate;
            $mediaFile->externalURLKey = '';
            $mediaFile->container = $flavorRequest->container;
            $mediaFile->videoPosterframe = '0';
            $mediaFile->videoDAR= '16.00';
            $mediaFile->videoFramerate= '23.98';
            $mediaFile->videoCodec= 'h264';
            $mediaFile->audioBitrate= '128';
            $mediaFile->audioBitrateMode= 'constant';
            $mediaFile->audioChannels= '2.0';
            $mediaFile->audioSamplerate= '44100';
            $mediaFile->audioCodec= 'aac';
            $mediaFile->streamable= 1;
            $mediaFile->synchronized= 1;
            $mediaFile->autoGenerated= 1;
            $mediaFile->active= 1;
            $mediaFile->save();
            return response()->json([
                'message' => 'Flavor Added.',
                'status_code' => 201
            ], 201);

        } catch( ModelNotFoundException $e ) {
            return $this->response->errorNotFound("Presentation {$flavorRequest->recordingId} not found");
        }
    }
}